# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b71174f664ed33f98334ecb226e92bd373fc59c7f86c80160e581cab96efc408a4f0d1e752c0fb776c2826cdd838c1da92c269ede196c438a88b009126287123

test:
  secret_key_base: 71baca9865e9a193a71f872d7d744ab381574bdb9ebb79e5812fc9c64e6bade5e4bcac1c745cca24ae01db4a02681122c9b900971b493fe916dd777afe12af02

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
